=== 000alen/Phaedra/backend/Phaedra/Notebook/notebook.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "phaedra.notebook.json",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "document_path": {
      "type": "string"
    },
    "pages": {
      "type": "array",
      "description": "The Pages in the Notebook",
      "items": {
        "$ref": "phaedra.page.json"
      }
    }
  },
  "required": ["id", "name", "pages"]
}

=== 000alen/Phaedra/backend/Phaedra/Tests/jupiter.json
{
  "id": "0",
  "name": "jupiter",
  "document_path": "jupiter.pdf",
  "pages": [
    {
      "id": "1",
      "data": {
        "source": "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets in the Solar System combined, but slightly less than one-thousandth the mass of the Sun. Jupiter is the third-brightest natural object in the Earth's night sky after the Moon and Venus. It has been observed since pre-historic times and is named after the Roman god Jupiter, the king of the gods, because of its observed size."
      },
      "cells": [
        {
          "id": "2",
          "data": {},
          "content": "Hello, world!"
        }
      ]
    }
  ]
}
